name: Unit test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    services:
      activemq:
        image: apache/activemq-classic:6.1.0
        ports:
          - 28161:8161
          - 21616:61616
      challenge-server:
        image: wiremock/wiremock:3.7.0
        ports:
          - 8222:8080
      recording-server:
        image: wiremock/wiremock:3.7.0
        ports:
          - 41375:8080
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # ~~~~~~~~~~~~~ Java setup ~~~~~~~~~~~~~
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: Display Java version
        run: java --version
        
      # ~~~~~~~~~~~~~ Test ~~~~~~~~~~~~~
      - name: Run gradle tests
        run: ./gradlew test
